### ISSUE TITLE
Dark mode broken in Brave browser

### ISSUE THREAD

**Issue by adaptpatrick** [team-reflect/webchat#1]
When attempting to use the extension in the Brave browser (1.71.118) I can't see any of the text:
![CleanShot 2024-10-30 at 09 43 32@2x](https://github.com/user-attachments/assets/1a40f415-2069-442a-a49b-3f60fe1daef2)

A minor issue but one I thought I should flag so that it can be addressed. 🙂

**Comment by majulahsingapuri** [comment]
Same for Chrome

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/2f6f899b-c8ea-4512-80ec-a38befdcc30b">

**Comment by maccman** [comment]
Go into Google extensions and try clicking update extensions. It's been fixed.
